name: Republican Party of San Diego County
slug: sd-county-republican-party
uri: https://sandiegorepublicans.org/
kind: party
about: |
  Official Republican Party affiliate for San Diego County. Endorses
  candidates on the SD County ballot.
