name: League of Women Voters of San Francisco
slug: lwv-san-francisco
uri: https://lwvsf.org/
kind: organization
about: |
  San Francisco chapter of the LWV. Like other LWV chapters, takes
  positions on ballot measures but does NOT endorse candidates.
