name: SF League of Pissed Off Voters
slug: sf-league-of-pissed-off-voters
uri: https://www.theleaguesf.org/
kind: organization
about: |
  San Francisco progressive voter guide. Famous for its irreverent
  endorsement zine and willingness to issue "No Endorsement" /
  "No Recommendation" decisions in races they don't take a position on.
